import os

DATABASE_SCHEME_NAME = os.environ['DATABASE_SCHEME_NAME']
BUCKET_NAME = os.environ['BUCKET_NAME']
DATABASE_SECRET_NAME = os.environ['DATABASE_SECRET_NAME']
CONTAINER_TIMEOUT = int(os.environ['CONTAINER_TIMEOUT'])
ESDL_QUEUE_URL = os.environ['ESDL_QUEUE_URL']
INIT_QUEUE_URL = os.environ['INIT_QUEUE_URL']